/** @type {import('tailwindcss').Config} */
export default {
    content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
    theme: {
        extend: {},
    },
    plugins: [require("@tailwindcss/typography"), require("daisyui")],
    daisyui: {
        themes: [
            "light",
            "dark",
            {
                oceanlight: {
                    "primary": "#3f83f8",
                    "primary-content": "#ffffff",
                    "secondary": "#f000b8",
                    "secondary-content": "#ffffff",
                    "accent": "#06b6d4",
                    "accent-content": "#ffffff",
                    "neutral": "#2b3544",
                    "neutral-content": "#d7dde4",
                    "base-100": "#ffffff",
                    "base-200": "#f2f2f2",
                    "base-300": "#e5e5e5",
                    "base-content": "#1f2937",
                    "info": "#0284c7",
                    "info-content": "#ffffff",
                    "success": "#16a34a",
                    "success-content": "#ffffff",
                    "warning": "#ea8c55",
                    "warning-content": "#ffffff",
                    "error": "#dc2626",
                    "error-content": "#ffffff",
                },
            },
            {
                oceandark: {
                    "primary": "#3b82f6",
                    "primary-content": "#1e1b4b",
                    "secondary": "#f000b8",
                    "secondary-content": "#160033",
                    "accent": "#0369a1",
                    "accent-content": "#cffafe",
                    "neutral": "#16213e",
                    "neutral-content": "#d7dde4",
                    "base-100": "#0f172a",
                    "base-200": "#1e293b",
                    "base-300": "#334155",
                    "base-content": "#f1f5f9",
                    "info": "#0284c7",
                    "info-content": "#ffffff",
                    "success": "#16a34a",
                    "success-content": "#ffffff",
                    "warning": "#ea8c55",
                    "warning-content": "#ffffff",
                    "error": "#dc2626",
                    "error-content": "#ffffff",
                },
            },
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
        ],
    },
    // darkMode: ['selector', '[data-theme="synthwave"]']
};
